fixtures:
  forge_modules:
    ntp:
      ref: '4.2.0'
      repo: puppetlabs/ntp
    owncloud:
      ref: '0.5.2'
      repo: shoekstra/owncloud
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
   owncloudstack: "#{source_dir}"
