fixtures:
  forge_modules:
    ntp:
      ref: '4.2.0'
      repo: puppetlabs/ntp
    timezone:
      ref: '3.4.0'
      repo: saz/timezone
    mysql:
      ref: '3.8.0'
      repo: puppetlabs/mysql
    sendmail:
      ref: '2.0.12'
      repo: example42/sendmail
    owncloud:
      ref: '0.5.2'
      repo: shoekstra/owncloud
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppi: "git://github.com/example42/puppi.git"
    monitor: "git://github.com/example42/puppet-monitor.git"
    firewall: "git://github.com/example42/puppet-firewall.git"
    iptables: "git://github.com/example42/puppet-iptables.git"
    concat: "git://github.com/example42/puppet-concat.git"
  symlinks:
   owncloudstack: "#{source_dir}"
